import type { LoggerOption } from '@alexaegis/logging';
import type { Argv } from 'yargs';
import type { CollectWorkspacePackagesOptions } from './collect-workspace-packages.function.options.js';

export type CollectWorkspacePackagesOptionsYargs = Argv<
	Omit<CollectWorkspacePackagesOptions, keyof LoggerOption>
>;

export const yargsForCollectWorkspacePackagesOptions = (
	yargs: Argv
): CollectWorkspacePackagesOptionsYargs => {
	return yargs
		.positional('cwd', {
			string: true,
			default: process.cwd(),
			description:
				'The directory in which a workspace is searched in for, can be anywhere inside ' +
				'a workspace, the last package.json up the directory tree will mark the ' +
				'root of the workspace.',
		})
		.option('force', {
			boolean: true,
			default: false,
			description: "Always overwrite target files even if it's occupied or non-autogenerated",
		})
		.option('dry', {
			boolean: true,
			default: false,
			description: "Don't actually do anything just log",
		})
		.option('skipWorkspaceRoot', {
			boolean: true,
			default: false,
			description: "Don't distribute to the root of the workspace",
		})
		.option('onlyWorkspaceRoot', {
			boolean: true,
			default: false,
			description:
				'Only distribute to the root of the workspace. (Skip all workspace packages)',
		})
		.option('dependencyCriteria', {
			default: [],
			coerce: (v) => v as string[],
			type: 'array',
			description:
				'Only distribute to workspace packages that have this dependency listed ' +
				'in their package.json file. Empty means no filtering is applied.',
		});
};
