name: ci

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

env:
  NPM_PACKAGE_ORG_PREFIX: '@alexaegis/'
  DEPLOY_ARTIFACT_DIR: 'coverage'
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: pnpm setup
        uses: pnpm/action-setup@v2
        with:
          run_install: false
      - name: output pnpm store directory
        id: pnpm-store
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.pnpm-store.outputs.STORE_PATH }}
            **/node_modules
            **/.turbo
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: install
        run: pnpm install
      - name: lint:tsc
        run: pnpm lint:tsc
      - name: lint:es
        run: pnpm lint:es
      - name: lint:depcheck
        run: pnpm lint:depcheck
      - name: lint:svelte
        run: pnpm lint:svelte
      - name: lint:style
        run: pnpm lint:style
      - name: lint:md
        run: pnpm lint:md
      - name: lint:md:workspace
        run: pnpm lint:md:workspace
      - name: lint:remark
        run: pnpm lint:remark
      - name: lint:remark:workspace
        run: pnpm lint:remark:workspace
      - name: lint:format
        run: pnpm lint:format
      - name: lint:format:workspace
        run: pnpm lint:format:workspace
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: pnpm setup
        uses: pnpm/action-setup@v2
        with:
          run_install: false
      - name: output pnpm store directory
        id: pnpm-store
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.pnpm-store.outputs.STORE_PATH }}
            **/node_modules
            **/.turbo
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: install
        run: pnpm install
      - name: test
        run: pnpm test
      - name: merge coverage
        run: pnpm posttest
      - name: upload coverage result to codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
      - name: upload coverage result to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage
      - name: prepare pages (use index.html as 404.html)
        if: |
          env.DEPLOY_ARTIFACT_DIR != '' &&
          github.ref_name == ${{ github.event.repository.default_branch }} &&
          github.event_name != 'pull_request'
        run: |
          cp ${{ env.DEPLOY_ARTIFACT_DIR }}/index.html ${{ env.DEPLOY_ARTIFACT_DIR }}/404.html
      - name: setup pages
        uses: actions/configure-pages@v3
        if: |
          env.DEPLOY_ARTIFACT_DIR != '' &&
          github.ref_name == ${{ github.event.repository.default_branch }} &&
          github.event_name != 'pull_request'
      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        if: |
          env.DEPLOY_ARTIFACT_DIR != '' && 
          github.ref_name == ${{ github.event.repository.default_branch }} && 
          github.event_name != 'pull_request'
        with:
          path: ${{ env.DEPLOY_ARTIFACT_DIR }}
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: pnpm setup
        uses: pnpm/action-setup@v2
        with:
          run_install: false
      - name: output pnpm store directory
        id: pnpm-store
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.pnpm-store.outputs.STORE_PATH }}
            **/node_modules
            **/.turbo
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: install
        run: pnpm install
      - name: build
        run: BASE_HREF="/${{ github.event.repository.name }}/" pnpm build
  deploy:
    name: deploy
    if: |
      env.DEPLOY_ARTIFACT_DIR != '' && 
      github.ref_name == ${{ github.event.repository.default_branch }} && 
      github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: [build, test, lint]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v2
  release:
    name: release
    if: |
      github.ref_name == ${{ github.event.repository.default_branch }} && 
      github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: [build, test, lint]
    strategy:
      matrix:
        artifact:
          [
            'common',
            'cli-tools',
            'coverage-tools',
            'fs',
            'logging',
            'workspace-tools',
          ]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: pnpm setup
        uses: pnpm/action-setup@v2
        with:
          run_install: false
      - name: output pnpm store directory
        id: pnpm-store
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.pnpm-store.outputs.STORE_PATH }}
            **/node_modules
            **/.turbo
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name:
          Check if ${{ env.NPM_PACKAGE_ORG_PREFIX }}${{ matrix.artifact }} is
          already deployed
        run: |
          VERSION=$(cat ".github/version.txt")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          IS_ON_NPM=$(if [ ! -z "$(npm view ${{ env.NPM_PACKAGE_ORG_PREFIX }}${{ matrix.artifact }}@$VERSION 2> /dev/null)" ]; then echo 'true'; else echo 'false'; fi)
          echo "IS_ON_NPM=$IS_ON_NPM" >> $GITHUB_ENV
          echo "was ${{ env.NPM_PACKAGE_ORG_PREFIX }}${{ matrix.artifact }}@$VERSION already on npm: $IS_ON_NPM"
      - name: install
        if: env.IS_ON_NPM != 'true'
        run: pnpm install
      - name:
          verify that ${{ env.NPM_PACKAGE_ORG_PREFIX }}${{ matrix.artifact }}
          builds
        if: env.IS_ON_NPM != 'true'
        run: |
          npx turbo run build-lib_ --scope="${{ matrix.artifact }}"
      - name:
          verify that ${{ env.NPM_PACKAGE_ORG_PREFIX }}${{ matrix.artifact }}
          lints are succeeding
        if: env.IS_ON_NPM != 'true'
        run: |
          npx turbo run lint_ --scope="${{ matrix.artifact }}"
      - name:
          verify that ${{ env.NPM_PACKAGE_ORG_PREFIX }}${{ matrix.artifact }}
          tests are succeeding
        if: env.IS_ON_NPM != 'true'
        run: |
          npx turbo run test --scope="${{ matrix.artifact }}"
      - name:
          release ${{ env.NPM_PACKAGE_ORG_PREFIX }}${{ matrix.artifact }} on npm
        if: env.IS_ON_NPM != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm config --location project set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          # --no-git-checks is enabled because `config set` creates/modifies .npmrc
          pnpm publish packages/${{ matrix.artifact }}/dist/ --no-git-checks --access public
